#!/usr/bin/env python3
"""Browser auto-login cookie harvester for YouTube (produces a yt-dlp cookiefile).

Uses Playwright (a headless Chromium) to sign into a Google/YouTube account
with plain credentials (email + password, optional 2FA code) and exports the
resulting session cookies as a Netscape-format cookies.txt. yt-dlp consumes
that file via its `cookiefile` option -- exactly the "--cookies" path yt-dlp's
own "Sign in to confirm you're not a bot" error recommends. A logged-in session
is a higher YouTube trust tier than anonymous requests, so it can get through
on IPs where anonymous requests are bot-checked.

This script is meant to run INSIDE the bot container at boot (see the Shahm
entrypoint). Because it logs in from a datacenter IP, Google may itself
challenge the login ("unusual traffic" checkpoint); in that case the script
reports it clearly and exits non-zero, and the operator can instead supply
cookies harvested from a clean IP via the YTDLP_COOKIES_B64 env var (the bot
decodes that into cookies.txt automatically).

Env vars:
    YTDLP_USERNAME          Google email
    YTDLP_PASSWORD          Google password
    YTDLP_TWOFA             optional 2FA / TOTP code
    YTDLP_COOKIE_MAX_WAIT   seconds to wait for each login step (default 35)

On success writes /app/cookies.txt (exit 0). On failure exits non-zero with a
clear message and saves a screenshot to /app/cookie_debug.png for inspection.
"""
import os
import sys
import time

from playwright.sync_api import sync_playwright

OUT = "/app/cookies.txt"
DEBUG_PNG = "/app/cookie_debug.png"
EMAIL = os.getenv("YTDLP_USERNAME", "").strip()
PASSWORD = os.getenv("YTDLP_PASSWORD", "").strip()
TWOFA = os.getenv("YTDLP_TWOFA", "").strip()
MAX_WAIT = int(os.getenv("YTDLP_COOKIE_MAX_WAIT", "35"))

# Keep cookies for these domains. yt-dlp's YouTube extractor needs the
# SID/HSID/SSID/APISID/SAPISID/LOGIN_INFO family (all on youtube.com or
# .google.com) plus __Secure-*APISID for authenticated innertube calls.
KEEP = ("youtube.com", "google.com", "googlevideo.com", "ytimg.com")

LOGIN_URL = (
    "https://accounts.google.com/v3/signin/identifier"
    "?continue=https%3A%2F%2Fwww.youtube.com%2F"
    "&service=youtube&flowName=GlifWebSignIn&flowEntry=ServiceLogin&hl=en"
)

SESSION_KEYS = (
    "SID", "HSID", "SSID", "APISID", "SAPISID", "LOGIN_INFO",
    "__Secure-1PAPISID", "__Secure-3PAPISID",
)


def log(msg):
    print(f"[get_cookies] {msg}", flush=True)


def write_netscape(cookies, path):
    lines = ["# Netscape HTTP Cookie File", "# Generated by get_cookies.py"]
    kept = 0
    for c in cookies:
        domain = c.get("domain", "") or ""
        name = c.get("name", "") or ""
        value = c.get("value", "") or ""
        if not domain or not name:
            continue
        if not any(k in domain for k in KEEP):
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        try:
            expires = int(c.get("expires", 0) or 0)
        except (TypeError, ValueError):
            expires = 0
        if expires < 0:
            expires = 0
        lines.append("\t".join([
            domain, include_sub, c.get("path", "/"), secure,
            str(expires), name, value,
        ]))
        kept += 1
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return kept


def wait_for_selector(page, selectors, desc=""):
    deadline = time.time() + MAX_WAIT
    while time.time() < deadline:
        for sel in selectors:
            try:
                el = page.query_selector(sel)
                if el and el.is_visible():
                    return el
            except Exception:
                pass
        time.sleep(0.5)
    log(f"timed out waiting for {desc or selectors}")
    return None


def click_first(page, selectors):
    for sel in selectors:
        try:
            el = page.query_selector(sel)
            if el:
                el.click()
                return True
        except Exception:
            pass
    return False


def main():
    if not (EMAIL and PASSWORD):
        log("YTDLP_USERNAME / YTDLP_PASSWORD not set; nothing to do")
        return 0

    with sync_playwright() as p:
        try:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-blink-features=AutomationControlled",
                    "--lang=en",
                ],
            )
        except Exception as e:
            log(f"chromium launch failed: {e!r}")
            return 2

        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
            locale="en-US",
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/131.0.0.0 Safari/537.36"
            ),
        )
        # Hide the automation fingerprint most likely to trip Google's checks.
        context.add_init_script(
            "Object.defineProperty(navigator, 'webdriver', {get: () => undefined});"
        )
        page = context.new_page()

        try:
            log("navigating to Google sign-in...")
            page.goto(LOGIN_URL, timeout=45000, wait_until="domcontentloaded")
        except Exception as e:
            log(f"goto failed: {e!r}")
            page.screenshot(path=DEBUG_PNG)
            browser.close()
            return 3

        # 1) Email
        email_box = wait_for_selector(
            page, ['input[type="email"]', "#identifierId"], desc="email field")
        if email_box is None:
            log("no email field found; title=" + repr(page.title()))
            page.screenshot(path=DEBUG_PNG)
            browser.close()
            return 4
        email_box.fill(EMAIL)
        if not click_first(page, ["#identifierNext", 'button[jsname]']):
            log("no 'Next' button after email")
            browser.close()
            return 4
        time.sleep(1.5)

        # 2) Password
        pass_box = wait_for_selector(
            page,
            ['input[type="password"]', "#password", 'input[name="password"]'],
            desc="password field",
        )
        if pass_box is None:
            log("no password field (checkpoint shown); title=" + repr(page.title()))
            page.screenshot(path=DEBUG_PNG)
            browser.close()
            return 5
        pass_box.fill(PASSWORD)
        if not click_first(page, ["#passwordNext", 'button[jsname]']):
            log("no 'Next' button after password")
            browser.close()
            return 5

        # 3) Wait for the session to settle, answering 2FA if we can.
        log("submitted credentials; waiting for session cookies...")
        deadline = time.time() + MAX_WAIT
        got = False
        while time.time() < deadline:
            cookies = context.cookies()
            names = {c["name"] for c in cookies}
            if "SID" in names and "SAPISID" in names:
                got = True
                break
            if TWOFA:
                totp = page.query_selector('input[name="totpPin"]') or page.query_selector(
                    'input[autocomplete="one-time-code"]')
                if totp:
                    totp.fill(TWOFA)
                    click_first(page, ["#totpNext", "button[jsname]"])
            time.sleep(1)

        if not got:
            text = page.content().lower()
            if "unusual traffic" in text or ("automated" in text and "detect" in text):
                log("BLOCKED: Google is showing an 'unusual traffic / verify '"
                    "you are not a bot' checkpoint - the datacenter-IP gate.")
            else:
                log("no SID/SAPISID after login; title=" + repr(page.title()))
            page.screenshot(path=DEBUG_PNG)
            browser.close()
            return 6

        # 4) Touch youtube.com so its session cookies are set.
        try:
            page.goto("https://www.youtube.com/", timeout=30000, wait_until="domcontentloaded")
            time.sleep(2)
        except Exception:
            pass

        n = write_netscape(context.cookies(), OUT)
        names = {c["name"] for c in context.cookies()}
        have = [k for k in SESSION_KEYS if k in names]
        log(f"wrote {n} cookies -> {OUT}; key session cookies: {have}")
        browser.close()
        if have:
            return 0
        log("session cookies missing; written cookies may not carry a valid login")
        return 7


if __name__ == "__main__":
    sys.exit(main())
