#!/usr/bin/env python3
"""Browser auto-login cookie harvester for YouTube (produces a yt-dlp cookiefile).

Uses Selenium driving the system Chromium (apt-installed in the image) to sign
into a Google/YouTube account with plain credentials (email + password, optional
2FA code) and exports the resulting session cookies as a Netscape-format
cookies.txt. yt-dlp consumes that file via its `cookiefile` option -- exactly
the "--cookies" path yt-dlp's own "Sign in to confirm you're not a bot" error
recommends. A logged-in session is a higher YouTube trust tier than anonymous
requests, so it can get through on IPs where anonymous requests are bot-checked.

This script is meant to run INSIDE the bot container at boot (see the Shahm
entrypoint). Because it logs in from a datacenter IP, Google may itself
challenge the login ("unusual traffic" checkpoint or a redirect to youtube.com's
bot-check interstitial); in that case the script reports it clearly and exits
non-zero, and the operator can instead supply cookies harvested from a clean IP
via the YTDLP_COOKIES_B64 env var (the bot decodes that into cookies.txt).

Env vars:
    YTDLP_USERNAME          Google email
    YTDLP_PASSWORD          Google password
    YTDLP_TWOFA             optional 2FA / TOTP code
    YTDLP_COOKIE_MAX_WAIT   seconds to wait for each login step (default 35)

On success writes /app/cookies.txt (exit 0). On failure exits non-zero with a
clear message and saves a screenshot to /app/cookie_debug.png for inspection.
"""
import os
import sys
import time
from urllib.parse import urlparse

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

OUT = "/app/cookies.txt"
DEBUG_PNG = "/app/cookie_debug.png"
EMAIL = os.getenv("YTDLP_USERNAME", "").strip()
PASSWORD = os.getenv("YTDLP_PASSWORD", "").strip()
TWOFA = os.getenv("YTDLP_TWOFA", "").strip()
MAX_WAIT = int(os.getenv("YTDLP_COOKIE_MAX_WAIT", "35"))

# Keep cookies for these domains. yt-dlp's YouTube extractor needs the
# SID/HSID/SSID/APISID/SAPISID/LOGIN_INFO family (all on youtube.com or
# .google.com) plus __Secure-*APISID for authenticated innertube calls.
KEEP = ("youtube.com", "google.com", "googlevideo.com", "ytimg.com")

LOGIN_URLS = (
    "https://accounts.google.com/v3/signin/identifier"
    "?continue=https%3A%2F%2Fwww.youtube.com%2F"
    "&service=youtube&flowName=GlifWebSignIn&flowEntry=ServiceLogin&hl=en",
    "https://accounts.google.com/ServiceLogin"
    "?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2F&hl=en",
    "https://accounts.google.com/signin",
)

SESSION_KEYS = (
    "SID", "HSID", "SSID", "APISID", "SAPISID", "LOGIN_INFO",
    "__Secure-1PAPISID", "__Secure-3PAPISID",
)


def log(msg):
    print(f"[get_cookies] {msg}", flush=True)


def write_netscape(cookies, path):
    lines = ["# Netscape HTTP Cookie File", "# Generated by get_cookies.py"]
    kept = 0
    for c in cookies:
        domain = c.get("domain", "") or ""
        name = c.get("name", "") or ""
        value = c.get("value", "") or ""
        if not domain or not name:
            continue
        if not any(k in domain for k in KEEP):
            continue
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        # Selenium reports the expiry under 'expiry' (seconds); some drivers
        # use 'expires'. 0 / missing means a session cookie.
        try:
            expires = int(c.get("expiry") or c.get("expires") or 0)
        except (TypeError, ValueError):
            expires = 0
        if expires < 0:
            expires = 0
        lines.append("\t".join([
            domain, include_sub, c.get("path", "/"), secure,
            str(expires), name, value,
        ]))
        kept += 1
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return kept


def _click(driver, css):
    try:
        driver.find_element(By.CSS_SELECTOR, css).click()
        return True
    except Exception:
        return False


def find_email(driver):
    """Return the email input, or None. Tries several entry points:
    1. The page is already the Google sign-in form.
    2. We landed on youtube.com (IP gate redirect) -> click its Sign-in link,
       which should open the Google form in the same tab.
    3. Alternative Google sign-in URLs.
    Logs where we actually are at each step for diagnosis.
    """
    try:
        box = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located(
                (By.CSS_SELECTOR, 'input[type="email"]')))
        return box
    except Exception:
        pass

    url = driver.current_url or ""
    title = driver.title or ""
    log(f"not on sign-in form; url={url!r} title={title!r}")

    if urlparse(url).netloc in ("youtube.com", "www.youtube.com"):
        log("redirected to youtube.com; trying its Sign-in link...")
        try:
            link = WebDriverWait(driver, 10).until(
                EC.element_to_be_clickable(
                    (By.CSS_SELECTOR, 'a[href*="accounts.google.com"]')))
            link.click()
        except Exception as e:
            log(f"no clickable sign-in link on youtube.com ({e!r})")
        try:
            box = WebDriverWait(driver, MAX_WAIT).until(
                EC.presence_of_element_located(
                    (By.CSS_SELECTOR, 'input[type="email"]')))
            return box
        except Exception:
            log("sign-in link did not lead to the email form; url="
                + repr(driver.current_url))
            return None

    for login_url in LOGIN_URLS[1:]:
        log("trying login URL: " + login_url.split("?")[0])
        try:
            driver.get(login_url)
            box = WebDriverWait(driver, MAX_WAIT).until(
                EC.presence_of_element_located(
                    (By.CSS_SELECTOR, 'input[type="email"]')))
            return box
        except Exception:
            continue
    log("all sign-in entry points failed; final url="
        + repr(driver.current_url) + " title=" + repr(driver.title))
    return None


def main():
    if not (EMAIL and PASSWORD):
        log("YTDLP_USERNAME / YTDLP_PASSWORD not set; nothing to do")
        return 0

    options = webdriver.ChromeOptions()
    options.binary_location = "/usr/bin/chromium"
    for arg in (
        "--headless=new",
        "--no-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--disable-blink-features=AutomationControlled",
        "--no-first-run",
        "--no-default-browser-check",
        "--lang=en",
        "--window-size=1280,800",
    ):
        options.add_argument(arg)
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)

    try:
        driver = webdriver.Chrome(
            service=Service("/usr/bin/chromedriver"), options=options)
    except Exception as e:
        log(f"chrome launch failed: {e!r}")
        return 2

    driver.set_page_load_timeout(45)
    try:
        # Hide the automation fingerprint most likely to trip Google's checks.
        driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
            "source": "Object.defineProperty(navigator,'webdriver',{get:()=>undefined})"
        })
    except Exception:
        pass

    try:
        log("navigating to Google sign-in...")
        driver.get(LOGIN_URLS[0])
    except Exception as e:
        log(f"goto failed: {e!r}")
        driver.save_screenshot(DEBUG_PNG)
        driver.quit()
        return 3

    email_box = find_email(driver)
    if email_box is None:
        src = (driver.page_source or "").lower()
        if "not a bot" in src or "unusual traffic" in src:
            log("BLOCKED: youtube.com 'not a bot / unusual traffic' interstitial "
                "- the datacenter-IP gate also blocks the login page itself.")
        driver.save_screenshot(DEBUG_PNG)
        driver.quit()
        return 4

    email_box.send_keys(EMAIL)
    _click(driver, "#identifierNext")
    time.sleep(1.5)

    try:
        WebDriverWait(driver, MAX_WAIT).until(
            EC.presence_of_element_located(
                (By.CSS_SELECTOR, 'input[type="password"]')))
    except Exception:
        log("no password field (checkpoint shown?); url="
            + repr(driver.current_url) + " title=" + repr(driver.title))
        driver.save_screenshot(DEBUG_PNG)
        driver.quit()
        return 5
    driver.find_element(By.CSS_SELECTOR, 'input[type="password"]').send_keys(PASSWORD)
    _click(driver, "#passwordNext")

    # Wait for the session to settle, answering 2FA if we can.
    log("submitted credentials; waiting for session cookies...")
    deadline = time.time() + MAX_WAIT
    got = False
    while time.time() < deadline:
        names = {c["name"] for c in driver.get_cookies()}
        if "SID" in names and "SAPISID" in names:
            got = True
            break
        if TWOFA:
            try:
                totp = driver.find_element(
                    By.CSS_SELECTOR,
                    'input[name="totpPin"], input[autocomplete="one-time-code"]',
                )
                totp.send_keys(TWOFA)
                _click(driver, "#totpNext")
            except Exception:
                pass
        time.sleep(1)

    if not got:
        src = (driver.page_source or "").lower()
        if "unusual traffic" in src or "not a bot" in src:
            log("BLOCKED: 'not a bot / unusual traffic' after login attempt "
                "(datacenter-IP gate).")
        else:
            log("no SID/SAPISID after login; url=" + repr(driver.current_url)
                + " title=" + repr(driver.title))
        driver.save_screenshot(DEBUG_PNG)
        driver.quit()
        return 6

    # Touch youtube.com so its session cookies are set.
    try:
        driver.get("https://www.youtube.com/")
        time.sleep(2)
    except Exception:
        pass

    n = write_netscape(driver.get_cookies(), OUT)
    names = {c["name"] for c in driver.get_cookies()}
    have = [k for k in SESSION_KEYS if k in names]
    log(f"wrote {n} cookies -> {OUT}; key session cookies: {have}")
    driver.quit()
    if have:
        return 0
    log("session cookies missing; written cookies may not carry a valid login")
    return 7


if __name__ == "__main__":
    sys.exit(main())
